version: "3.9"

services:
  # ===================== PROD =====================
  postgres-db:
    profiles: ["prod"]
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${VECTOR_DB_NAME}
      POSTGRES_USER: ${VECTOR_DB_USER}
      POSTGRES_PASSWORD: ${VECTOR_DB_PASSWORD}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${VECTOR_DB_USER} -d ${VECTOR_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    profiles: ["prod"]
    build: .
    restart: always
    env_file: .env
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/"]
      interval: 60s
      timeout: 3s
      retries: 10
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432

  # ===================== DEV =====================
  postgres-db-dev:
    profiles: ["dev"]
    image: postgres:16-alpine
    restart: always
    environment:
      VECTOR_DB_HOST: postgres-db-dev
      POSTGRES_DB: ${VECTOR_DB_NAME}
      POSTGRES_USER: ${VECTOR_DB_USER}
      POSTGRES_PASSWORD: ${VECTOR_DB_PASSWORD}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${VECTOR_DB_USER} -d ${VECTOR_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  web-dev:
    profiles: ["dev"]
    build: .
    restart: always
    env_file: .env
    depends_on:
      postgres-db-dev:
        condition: service_healthy
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/"]
      interval: 60s
      timeout: 3s
      retries: 10
    environment:
      VECTOR_DB_HOST: postgres-db-dev
      VECTOR_DB_PORT: 5432
      DB_HOST: postgres-db-dev
      DB_PORT: 5432

volumes:
  postgres_data:
  postgres_data_dev:
